#Run and build gerald77/picapport

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'gerald77/picapport'
  dockerHub: 'gerald77'

steps:
- task: Docker@2
  displayName: Build debian-ssh
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile
    tags: latest
- task: Docker@2
  displayName: Push debian-ssh
  inputs:
    containerRegistry: |
      $(dockerHub)
    repository: $(imageName)
    command: push
    tags: latest